version: "3.8"
services:
  vim:
    build: ./vim
    # command: make setup install; vim ../php/src/hello.php
    tty: true
    volumes:
      - .:/app

  php:
    build: ./php
    # command: make run
    tty: true
    volumes:
      - .:/app
      # - ./php/usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
