version: "3.8"
services:
  vim:
    build: ./vim
    tty: true
    volumes:
      - .:/app

  php:
    build: ./php
    tty: true
    volumes:
      - .:/app
      # - ./php/usr/local/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
