FROM debian:10.5

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      make \
      less \
      git \
      python3 \
      python3-dev \
      build-essential \
      libncurses-dev \
      locales \
      && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen en_US.UTF-8

COPY ./deps/vim/vim /tmp/vim

RUN cd /tmp/vim && \
    ./configure \
      # --prefix=#{HOMEBREW_PREFIX} \
      # --mandir=#{man} \
      --enable-multibyte \
      --with-tlib=ncurses \
      # --with-compiledby=Homebrew \
      --enable-cscope \
      --enable-terminal \
      # --enable-perlinterp \
      # --enable-rubyinterp \
      --enable-python3interp \
      --enable-gui=no \
      --without-x \
      # --enable-luainterp \
      # --with-lua-prefix=#{Formula["lua"].opt_prefix} \
      --with-python3-config-dir=/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/ \
      --enable-fail-if-missing \
      && \
    make -C src && \
    make -C src install

RUN rm -rf /tmp/vim && \
    apt-get auto-remove -y && \
    apt-get clean

WORKDIR /work/vim
